services:
  - type: web
    name: email-classification-system
    runtime: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt &&
      python -c "import nltk; nltk.download('punkt', quiet=True); nltk.download('stopwords', quiet=True); nltk.download('rslp', quiet=True)" || true
    startCommand: python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: MODEL_CACHE_DIR
        value: /tmp/models_cache
      - key: UPLOAD_DIR
        value: /tmp/uploads
    healthCheckPath: /health
    disk:
      name: email-classification-storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
