services:
  - type: web
    name: mail-execute
    env: python
    buildCommand: pip install -r requirements-production.txt
    startCommand: python -m uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_OPENAI
        value: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false